allowBuilds:
  '@swc/core': set this to true or false
  protobufjs: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@temporalio/activity@1.24.0'
  - '@temporalio/client@1.24.0'
  - '@temporalio/common@1.24.0'
  - '@temporalio/core-bridge@1.24.0'
  - '@temporalio/external-storage-gcs-google-sdk@1.24.0'
  - '@temporalio/external-storage-gcs@1.24.0'
  - '@temporalio/external-storage-s3-aws-sdk@1.24.0'
  - '@temporalio/external-storage-s3@1.24.0'
  - '@temporalio/nexus@1.24.0'
  - '@temporalio/plugin@1.24.0'
  - '@temporalio/proto@1.24.0'
  - '@temporalio/worker@1.24.0'
  - '@temporalio/workflow@1.24.0'
