import * as assert from 'assert';
import * as wf from '@temporalio/workflow';
import { Feature } from '@temporalio/harness';
import * as sercontext from '../sercontext/sercontext';

const WORKFLOW_INPUT = 'hello';
const CHILD_RESULT_TAG = '|child';

export async function workflow(input: string): Promise<string> {
  // No explicit workflowId: the SDK assigns one, and the child's payloads must
  // still be converted with that generated ID.
  return wf.executeChild(childWorkflow, {
    args: [input],
  });
}

export async function childWorkflow(input: string): Promise<string> {
  return input + CHILD_RESULT_TAG;
}

export const feature = new Feature({
  workflow,
  workflowStartOptions: { args: [WORKFLOW_INPUT] },
  dataConverter: { payloadCodecs: [new sercontext.SigningCodec()] },
  checkResult: async (runner, handle) => {
    assert.equal(await handle.result(), WORKFLOW_INPUT + CHILD_RESULT_TAG);

    const parentEvents = await runner.getHistoryEvents(handle);

    // The child ID is generated by the SDK, so discover it from the parent history.
    const childStartedInParent = sercontext.findEvent(
      parentEvents,
      'ChildWorkflowExecutionStarted',
      (e) => !!e.childWorkflowExecutionStartedEventAttributes,
    ).childWorkflowExecutionStartedEventAttributes;
    const childId = childStartedInParent?.workflowExecution?.workflowId ?? '';

    // The generated child ID differs from the parent's, and carries the child's own signature.
    assert.notEqual(childId, handle.workflowId);
    assert.notEqual(childId, '');
    const expected = sercontext.workflowSignature(runner.options.namespace, childId);
    assert.notEqual(expected, sercontext.workflowSignature(runner.options.namespace, handle.workflowId));

    const initiated = sercontext.findEvent(
      parentEvents,
      'StartChildWorkflowExecutionInitiated',
      (e) => !!e.startChildWorkflowExecutionInitiatedEventAttributes,
    ).startChildWorkflowExecutionInitiatedEventAttributes;
    assert.equal(sercontext.firstSignature(initiated?.input), expected);

    const childCompleted = sercontext.findEvent(
      parentEvents,
      'ChildWorkflowExecutionCompleted',
      (e) => !!e.childWorkflowExecutionCompletedEventAttributes,
    ).childWorkflowExecutionCompletedEventAttributes;
    assert.equal(sercontext.firstSignature(childCompleted?.result), expected);

    const childEvents = await runner.getHistoryEvents(runner.client.workflow.getHandle(childId));
    const childStarted = sercontext.findEvent(
      childEvents,
      'WorkflowExecutionStarted',
      (e) => !!e.workflowExecutionStartedEventAttributes,
    ).workflowExecutionStartedEventAttributes;
    assert.equal(sercontext.firstSignature(childStarted?.input), expected);
  },
});
