package child_workflow_payloads_default_id

import (
	"context"
	"time"

	"github.com/temporalio/features/features/serialization_context/sercontext"
	"github.com/temporalio/features/harness/go/harness"
	historypb "go.temporal.io/api/history/v1"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/workflow"
)

const (
	workflowInput  = "hello"
	childResultTag = "|child"
)

var Feature = harness.Feature{
	Workflows:     []interface{}{Workflow, ChildWorkflow},
	ClientOptions: sercontext.ClientOptions(),
	Execute:       harness.ExecuteWithArgs(Workflow, workflowInput),
	CheckResult:   CheckResult,
	CheckHistory:  harness.NoHistoryCheck,
}

func Workflow(ctx workflow.Context, input string) (string, error) {
	// No explicit workflow ID: the SDK assigns a deterministic one, and the
	// child's payloads must still be converted with that generated ID.
	opts := workflow.ChildWorkflowOptions{
		WorkflowRunTimeout: time.Minute,
	}
	var result string
	err := workflow.ExecuteChildWorkflow(
		workflow.WithChildOptions(ctx, opts), ChildWorkflow, input).Get(ctx, &result)
	return result, err
}

func ChildWorkflow(ctx workflow.Context, input string) (string, error) {
	return input + childResultTag, nil
}

func CheckResult(ctx context.Context, runner *harness.Runner, run client.WorkflowRun) error {
	var result string
	if err := run.Get(ctx, &result); err != nil {
		return err
	}
	runner.Require.Equal(workflowInput+childResultTag, result)

	parentEvents, err := sercontext.Events(ctx, runner.Client, run.GetID(), run.GetRunID())
	if err != nil {
		return err
	}

	// The child ID is generated by the SDK, so discover it from the parent history.
	childStarted, err := sercontext.FindEvent(parentEvents, "ChildWorkflowExecutionStarted", func(e *historypb.HistoryEvent) bool {
		return e.GetChildWorkflowExecutionStartedEventAttributes() != nil
	})
	if err != nil {
		return err
	}
	childID := childStarted.GetChildWorkflowExecutionStartedEventAttributes().GetWorkflowExecution().GetWorkflowId()

	// The generated child ID differs from the parent's, and its payloads carry the child's own signature.
	runner.Require.NotEqual(run.GetID(), childID)
	runner.Require.NotEmpty(childID)
	expected := sercontext.WorkflowSignature(runner.Namespace, childID)
	runner.Require.NotEqual(sercontext.WorkflowSignature(runner.Namespace, run.GetID()), expected)

	initiated, err := sercontext.FindEvent(parentEvents, "StartChildWorkflowExecutionInitiated", func(e *historypb.HistoryEvent) bool {
		return e.GetStartChildWorkflowExecutionInitiatedEventAttributes() != nil
	})
	if err != nil {
		return err
	}
	runner.Require.Equal(expected,
		sercontext.FirstSignature(initiated.GetStartChildWorkflowExecutionInitiatedEventAttributes().GetInput()))

	childCompleted, err := sercontext.FindEvent(parentEvents, "ChildWorkflowExecutionCompleted", func(e *historypb.HistoryEvent) bool {
		return e.GetChildWorkflowExecutionCompletedEventAttributes() != nil
	})
	if err != nil {
		return err
	}
	runner.Require.Equal(expected,
		sercontext.FirstSignature(childCompleted.GetChildWorkflowExecutionCompletedEventAttributes().GetResult()))

	childEvents, err := sercontext.Events(ctx, runner.Client, childID, "")
	if err != nil {
		return err
	}
	childWfStarted, err := sercontext.FindEvent(childEvents, "WorkflowExecutionStarted", func(e *historypb.HistoryEvent) bool {
		return e.GetWorkflowExecutionStartedEventAttributes() != nil
	})
	if err != nil {
		return err
	}
	runner.Require.Equal(expected,
		sercontext.FirstSignature(childWfStarted.GetWorkflowExecutionStartedEventAttributes().GetInput()))

	return nil
}
