name: 'Run Temporal Dev Server'
description: 'Run a local instance of temporal server using the temporal repository'
inputs:
  repo-path:
    description: 'The path to use when checking out the server repo'
    type: string
    default: "temporalio/temporal"
  repo-ref:
    description: 'The ref to use when checking out the server repo'
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out server repo
      uses: actions/checkout@v3
      with:
        repository: temporalio/temporal
        path: temporal-server
        ref: ${{ inputs.repo-ref }}

    - name: Build server instance
      run: make bins
      working-directory: temporal-server

    - name: Run server instance
      run: make start-sqlite
      working-directory: temporal-server
