# This is meant to be used in conjunction with a docker compose file from the server repo
# (for dependencies) and a docker image for running server itself.
version: '3.5'

services:
  temporal-server:
    image: temporaliotest/auto-setup:${IMAGE_TAG:-latest}
    environment:
      - CASSANDRA_SEEDS=cassandra
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    ports:
      - '7233:7233'
    depends_on:
      - cassandra
      - elasticsearch
    networks:
      - temporal-dev-network

  features-tests-go:
    image: temporaliotest/features:go
    environment:
      - WAIT_EXTRA_FOR_NAMESPACE
    command: ['--server', 'temporal-server:7233', '--namespace', 'default']
    depends_on:
      - temporal-server
    networks:
      - temporal-dev-network

  features-tests-py:
    image: temporaliotest/features:py
    environment:
      - WAIT_EXTRA_FOR_NAMESPACE
    command: ['--server', 'temporal-server:7233', '--namespace', 'default']
    depends_on:
      - temporal-server
    networks:
      - temporal-dev-network

  features-tests-ts:
    image: temporaliotest/features:ts
    environment:
      - WAIT_EXTRA_FOR_NAMESPACE
    command: ['--server', 'temporal-server:7233', '--namespace', 'default']
    depends_on:
      - temporal-server
    networks:
      - temporal-dev-network

  features-tests-java:
    image: temporaliotest/features:java
    environment:
      - WAIT_EXTRA_FOR_NAMESPACE
    command: ['--server', 'temporal-server:7233', '--namespace', 'default']
    depends_on:
      - temporal-server
    networks:
      - temporal-dev-network

  features-tests-cs:
    image: temporaliotest/features:cs
    environment:
      - WAIT_EXTRA_FOR_NAMESPACE
    command: ['--server', 'temporal-server:7233', '--namespace', 'default']
    depends_on:
      - temporal-server
    networks:
      - temporal-dev-network
